### PR TITLE
add tables 'posts' 'comments', see db/migrate/

### PR DESCRIPTION
**Pull request by EllyChanx**
- add tables 'posts' and 'comments'
- see tables details in db/migrate
- run "rails db:migrate" to migrate create new tables
- run "rails db" then "\dt" to see newly created tables

### CODE REVIEW

**Review by lucafrancesc — APPROVED** [review]
Good

**Comment by mateuszstacel** [comment]
Good Job !

**Review by mateuszstacel — APPROVED** [review]
Good !

**Review by LornaHa — APPROVED** [review]
Good Job!

**Pull request merged**
